src/Update.cs
test/UnitTests/UpdateTests.cs

Apparently the GitHub Pages redirect will go from https->http if you use the <username>.github.io URL instead of the custom domain that's associated with the repo. This breaks dnvm because it doesn't follow https->http redirects.

Update releases URL and add test

---

src/CommandLine/ArgumentSyntax.cs
src/Update.cs
test/PublishTests/PublishTests.csproj
test/PublishTests/UpdateTests.cs

The update command tries to validate the downloaded dnvm binary to ensure that it can do basic things. One thing it checks is whether it can print a help message which contains the 'usage: ' string. However, previously dnvm printed the usage message to stderr instead of stdout, so the validation failed. The handler has been updated to print help to stdout iff it's requested.

Fix binary validation

---

src/env.sh

When installing dotnet locally (i.e., not in the hardcoded global install path) the apphost will not be able to find the dotnet runtime unless DOTNET_ROOT is set. This sets DOTNET_ROOT when installing to a local path to ensure that apphosts will work.

Set DOTNET_ROOT in env.sh

---

.github/workflows/makeRelease.yml
.github/workflows/webUpdate.yml

Instead of publishing gh-pages on creation of the tag, publishing gh-pages will happen when the release is actually published.

Make gh-pages publish on Release publish

---

src/CommandLineOptions.cs
src/Install.cs

The dotnet feeds include extra entries in the query string, which isn't supported using Uri relative path construction.

Go back to strings for feed construction

---

src/Update.cs
src/Utilities.cs

I previously changed the arch in CurrentRID to be
x64 if the current platform is OSX, but that accidentally changed the SDK install to download only x64 SDks, when ARM64 is needed.

Fix arch fetching

---

src/Install.cs

The previous install path was the .dotnet directory in /Users/angocke, but that isn't a standard directory, and it is used by many other dotnet tools. The new path is a dnvm directory in LocalApplicationData, which maps to appropriate user-local directories on all platforms.

Change the default install path

---

src/CommandLineOptions.cs
src/Install.cs
src/Utilities.cs
test/UnitTests/InstallTests.cs

During testing we don't want to update the user environment (bash files, environment variables). Also fix a bug where we were pulling the process architecture instead of the machine architecture.

Add UpdateUserEnvironment install flag

---

src/Install.cs

All usages of GetFolderPath in dnvm don't care if the path exists, and if it doesn't it will create it itself or error.

Specify SpecialFolderOption.DoNotVerify

---

.github/workflows/ci.yml
.github/workflows/makeRelease.yml
.github/workflows/publish.yml
.github/workflows/webUpdate.yml
nuget.config
publish.sh
src/dnvm.csproj
test/PublishTests/PublishTests.csproj
test/Shared/Dnvm.Test.Shared.csproj
test/UnitTests/UnitTests.csproj

Mac is not supported on .NET 7, but we were using unsupported package builds. It will be supported in net8, so upgrading to net8 packages keeps us up to date and allows targeting arm64, which didn't even have preview packages before.

Use net8 ILC on Mac

---

src/CommandLine/ArgumentSyntax_Definers.cs
src/CommandLineOptions.cs
src/DefaultConfig.cs
src/Install.cs
src/Program.cs
src/Update.cs
src/VersionInfo.cs
src/dnvm.csproj
test/PublishTests/UpdateTests.cs
test/Shared/MockServer.cs
test/UnitTests/InstallTests.cs
test/UnitTests/UpdateTests.cs

Dotnet publishes an official index that includes all current releases, including official preview releases. This can be used instead of hitting multiple REST endpoints.

Grab releases info from official index

---

test/Shared/Assets.cs
test/Shared/DisposableDirectory.cs
test/Shared/MockServer.cs
test/Shared/assets/fakesdk-42.42.42/dotnet

Gets rid of dead code, and it should fix an inter-process race condition that was sometimes causing failures on Windows.

Clean up test artifact creation

---

.github/workflows/ci.yml
.github/workflows/makeRelease.yml
.github/workflows/publish.yml
src/dnvm/Install.cs
src/dnvm/Update.cs
src/dnvm/Utilities.cs
src/dnvm/env.sh
test/IntegrationTests/SelfInstallTests.cs

Using a symlink allows for installing SDKs to multiple directories and retargeting to individual installs based on user commands.

Use a symlink for selecting the right SDK install

---

src/dnvm/CommandLineOptions.cs
src/dnvm/Install.cs
src/dnvm/ProcUtil.cs
src/dnvm/Update.cs
test/IntegrationTests/UpdateTests.cs
test/Shared/Assets.cs

Currently self-update is something done entirely by the originating binary -- it checks for available updates, downloads the updaate, and swaps the new binary in for the old.
This means that the new binary doesn't have a chance to run any program logic.
The new model is to download the new binary, and then run it in an installer mode. This will let the binary install itself, running whatever's necessary to do so.

Rework self-update

---

src/dnvm/DotnetReleasesIndex.cs
src/dnvm/Manifest.cs
test/UnitTests/UpdateTests.cs

This function is meant to find the newest release in a given channel. It now properly excludes preview releases, unless the channel is a preview channel.

Fix GetLatestReleaseForChannel

---

src/Vfs/IVfs.cs
src/Vfs/MemoryFs.cs
src/Vfs/OsFs.cs
src/Vfs/Vfs.csproj
src/Vfs/VfsPath.cs
src/dnvm/DnvmHome.cs
src/dnvm/List.cs
src/dnvm/Manifest.cs
src/dnvm/Program.cs
src/dnvm/dnvm.csproj
test/UnitTests/ListTests.cs
test/UnitTests/VfsTests.cs

Basic VFS abstraction that supports in-memory files. Only used for ListTests right now, but should eventually be used for all file I/O in dnvm.

Add VFS abstraction for testing

---

src/dnvm/InstallCommand.cs
src/dnvm/Utilities/Utilities.cs
test/UnitTests/SelectTests.cs

The dotnet.exe muxer doesn't work properly with symlinks on Windows, so a cmd file is the best solution.

Use a cmd file on windows instead of symlink

---

test/Shared/MockServer.cs

HttpListenerException is thrown from GetContextAsync when listening is stopped. We can catch it and proceed without error.

Catch HttpListenerException when stopping

---

test/Shared/MockServer.cs

Chatch all exceptions from _listener.GetContextAsync when the mock server is being disposed.

Fix more race conditions in closing HttpListener

---

src/dnvm/CommandLineArguments.cs
src/dnvm/DnvmEnv.cs
src/dnvm/Manifest.cs
src/dnvm/Program.cs
src/dnvm/UntrackCommand.cs
test/UnitTests/UntrackTests.cs

The untrack command will remove a channel from the tracked list, meaning that the update command will no longer pull SDKs from the given channel. This also gives the opportunity to retrack the given channel and assign it to a different directory.

Add untrack command

---

src/dnvm/ListCommand.cs
src/dnvm/ManifestSchema/Manifest.cs
src/dnvm/ManifestSchema/ManifestV3.cs
src/dnvm/Utilities/EqArray.cs
src/dnvm/Utilities/Utilities.cs
src/dnvm/dnvm.csproj
test/UnitTests/ListTests.cs
test/UnitTests/ManifestTests.cs

SDKs may be installed via tracking a channel. Since directories aren't strictly tied to channels, installation directory isn't a unique indicator of which channel it was installed from. This is useful information, and it may be required for later functionality.

Record channel for InstalledSdk in manifest

---

src/dnvm/DnvmEnv.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/ListCommand.cs
src/dnvm/ManifestSchema/Manifest.cs
src/dnvm/ManifestSchema/ManifestV4.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/SelectCommand.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/UntrackCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/EqArray.cs
src/dnvm/Utilities/Utilities.cs
test/Shared/MockServer.cs
test/UnitTests/InstallTests.cs
test/UnitTests/ListTests.cs
test/UnitTests/ManifestTests.cs
test/UnitTests/SelectTests.cs
test/UnitTests/UpdateTests.cs

In order to implement uninstall, we need versions for each of the components that make up an SDK. Those versions were not previously stored in the manifest, and not available from the APIs we were calling. This PR changes the manifest to contain these versions and adds support for pulling more detailed information from the index.

Add more versions to the Manifest

---

src/dnvm/ManifestSchema/Manifest.cs
src/dnvm/ManifestSchema/ManifestV3.cs
test/UnitTests/ManifestTests.cs

If a particular directory tracks multiple channels, the current mapping doesn't work. This works around the problem for the most common instances.

Fix channel mapping issue

---

src/dnvm/ManifestUtils.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
test/UnitTests/InstallTests.cs
test/UnitTests/SelectTests.cs

Previously, preview versions were installed to the 'preview' folder to separate from the release versions. There are drawbacks to installing in the same folder, but they can mostly be addressed by using global.json. Using one folder is also preferred for the official product, so this matches the expected product layout.

Install preview SDKs to the default folder

---

src/dnvm/CommandLineArguments.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/UninstallCommand.cs
src/dnvm/Utilities/Utilities.cs
test/Shared/Assets.cs
test/Shared/Dnvm.Test.Shared.csproj
test/Shared/MockServer.cs
test/UnitTests/UninstallTests.cs

The 'dnvm install' command mostly starts tracking a channel, and only incidentally installs an SDK.
Also adds an uninstall command that can remove a particular SDK.

Rename 'install' to 'track' and add 'uninstall'

---

src/dnvm/CommandLineArguments.cs
src/dnvm/PruneCommand.cs
src/dnvm/UninstallCommand.cs
test/UnitTests/PruneTests.cs

Prune removes SDKs that have a lower patch or preview version than another SDK installed in the same directory.

Add prune command

---

src/dnvm/Channel.cs
src/dnvm/CommandLineArguments.cs
src/dnvm/ListCommand.cs
src/dnvm/ManifestSchema/ManifestV5.cs
src/dnvm/ManifestUtils.cs
src/dnvm/ScalarDeserializer.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/dnvm.csproj
test/IntegrationTests/SelfInstallTests.cs
test/Shared/MockServer.cs
test/Shared/TestUtils.cs
test/UnitTests/ListTests.cs
test/UnitTests/ManifestTests.cs
test/UnitTests/PruneTests.cs
test/UnitTests/SelectTests.cs
test/UnitTests/TrackTests.cs
test/UnitTests/UninstallTests.cs
test/UnitTests/UntrackTests.cs
test/UnitTests/UpdateTests.cs

This allows you to track versions like '6.0' as though they were a named channel.

Add initial support for tracking minor-major versions

---

src/dnvm/InstallCommand.cs
src/dnvm/Utilities/Utilities.cs

Change HttpClient.GetAsync call to pass ResponseHeadersRead. This allows for tracking download progress incrementally.

Fix download progress

---

src/dnvm/DnvmEnv.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/ManifestUtils.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/Utilities.cs
src/dnvm/dnvm.csproj
test/IntegrationTests/VersionCheck.cs
test/Shared/MockServer.cs
test/Shared/TestOptions.cs
test/UnitTests/InstallTests.cs
test/UnitTests/ManifestTests.cs

Normally we rely on the .NET releases index to find both the version information for the requested SDK and the download URL. In the case of daily builds, none of that information is published to an index. Therefore we need to use other resources. For the URL, there is a known pattern that is implemented by dotnet-install.sh that we copy. For the version information, there is an undocumented `productCommit-{RID}.json` file that appears to contain the necessary information. Together, these items should allow us to install and uninstall daily builds.

Fix installing daily builds

---

src/dnvm/Channel.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/TrackCommand.cs
test/Shared/MockServer.cs
test/UnitTests/TrackTests.cs
test/UnitTests/UpdateTests.cs

It's common for some channels (e.g., preview) to not have builds for a period of time when the previous channel has gone out of support, but the new one has not had any releases yet. Tracking shouldn't depend on installing an SDK, so there's no reason we can't allow tracking to proceed.
Fixes #135

Fix tracking channels with no builds

---

src/dnvm/CommandLineArguments.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/Utilities/Utilities.cs
test/UnitTests/CommandLineTests.cs

The output is now using the display names, but 'track' will accept any lower-case equivalent channel name when tracking.
Fixes #134

Fix 'track' output and formatting

---

src/dnvm/CommandLine/ArgumentParser.cs
src/dnvm/CommandLine/ArgumentSyntax.cs
src/dnvm/CommandLine/ArgumentSyntax_Definers.cs
src/dnvm/CommandLine/Strings.cs

When doing
```text
dvnm install
```
the following exception is raised
```text
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Dnvm.InstallCommand.<Run>d__1.MoveNext() + 0x198
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x100
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x68
at Dnvm.Program.<Dnvm>d__3.MoveNext() + 0x2f0
--- End of stack trace from previous location ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x24
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Tas …
```

Slightly more robust parameter parsing

---

Directory.Packages.props
src/Serde.CmdLine/Attributes.cs
src/Serde.CmdLine/CmdLine.cs
src/Serde.CmdLine/Deserializer.cs
src/Serde.CmdLine/UnionSerdeInfo.cs
src/Serde.CmdLine/Utils.cs
src/dnvm/Channel.cs
src/dnvm/CommandLineArguments.cs
src/dnvm/ScalarDeserializer.cs
src/dnvm/SerdeWraps/SdkDirNameProxy.cs
src/dnvm/SerdeWraps/SemVersionSerdeWrap.cs
src/dnvm/Utilities/EqArray.cs
test/Serde.CmdLine.Test/SubCommandTests.cs
test/UnitTests/CommandLineTests.cs

Moves more argument parsing over to Serde.CmdLine and adds support for unions using the new Serde ISerdeInfo interface.
Also builds help text entirely out of ISerdeInfoProvider, which allows it to be built separate from deserialization, fully statically.

Move more code to Serde.CmdLine

---

.github/workflows/publish.yml

Ubuntu CI runners have been upgraded to noble, old packages don't work anymore.

Upgrade arm64 to use noble packages

---

src/dnvm/CommandLineArguments.cs
src/dnvm/DnvmEnv.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/ManifestSchema/ManifestV3.cs
src/dnvm/ManifestSchema/ManifestV5.cs
src/dnvm/Program.cs
src/dnvm/RestoreCommand.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/UninstallCommand.cs
src/dnvm/Utilities/Result.cs
src/dnvm/Utilities/Utilities.cs
src/dnvm/dnvm.csproj
test/IntegrationTests/SelfInstallTests.cs
test/IntegrationTests/VersionCheck.cs
test/Shared/MockServer.cs
test/Shared/TestOptions.cs
test/Shared/TestUtils.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/InstallTests.cs
test/UnitTests/ListTests.cs
test/UnitTests/ManifestTests.cs
test/UnitTests/RestoreTests.cs
test/UnitTests/SelectTests.cs
test/UnitTests/TrackTests.cs
test/UnitTests/UninstallTests.cs
test/UnitTests/UpdateTests.cs

The restore command downloads a compatible SDK listed in a global.json file in the current working directory or parent thereof. The SDK is expanded into a `.dotnet` directory next to the global.json file. This command does not affect the set of installed SDKs.
Fixes https://github.com/dn-vm/dnvm/issues/165

Add 'restore' command to Dnvm

---

src/dnvm/SelfInstallCommand.cs

Because `args.UpdateUserEnvironment` is true by default, the self install command would always presume that the user's environment should be updated, regardless of input. Fixes https://github.com/dn-vm/dnvm/issues/171.

Ensure that updateUserEnvironment respects user input

---

.github/workflows/ci.yml
src/dnvm/RestoreCommand.cs
test/UnitTests/RestoreTests.cs

The bugs are
1. Restore did not narrow down to a single zip/targz suffix
2. Pre-5.0 release entries are not compatible with the new JSON schema. This hasn't really been fixed, just worked-around by only looking at major-minor versions at least as high as the version mentioned in the global.json. The assumption is that people aren't trying to install pre-3.0 SDKs (probably wrong, but left for later).

Fix two bugs in restore

---

src/dnvm/DnvmEnv.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/ManifestSchema/ManifestV5.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/RestoreCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/CancelScope.cs
src/dnvm/Utilities/Extensions.cs
src/dnvm/Utilities/ScopedHttpClient.cs
src/dnvm/Utilities/Utilities.cs
test/IntegrationTests/UpdateTests.cs
test/IntegrationTests/VersionCheck.cs
test/UnitTests/ManifestTests.cs
test/UnitTests/UpdateTests.cs

This moves the repo to using a CancelScope instead of passing around CancellationTokens. This is a design pattern from structured concurrency. It also introduces a ScopedHttpClient which respects CancelScope. The ScopedHttpClient is also attached to a DnvmEnv, instead of being a global static, which allows for testing and more configuration options.
Lastly, the ScopedHttpClient now no longer has a 100 second global timeout. Instead, timeouts are regulated per-scope or through the specialty GetStringAsync method (which has a default timeout).

Adopt CancelScope and ScopedHttpClient

---

src/dnvm/CommandLineArguments.cs
src/dnvm/DnvmReleases.cs
src/dnvm/ManifestSchema/ManifestV7.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/ProcUtil.cs
test/IntegrationTests/SelfInstallTests.cs
test/IntegrationTests/UpdateTests.cs
test/Shared/MockServer.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/UpdateTests.cs

Adds a new section for preview versions to the dnvm releases json file. This will allow for two release trains: stable and preview.

Allow enabling preview versions

---

.github/workflows/ci.yml
src/dnvm/CommandLineArguments.cs
src/dnvm/DnvmReleases.cs
src/dnvm/ManifestSchema/ManifestV7.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/ProcUtil.cs
test/IntegrationTests/SelfInstallTests.cs
test/IntegrationTests/UpdateTests.cs
test/Shared/MockServer.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/UpdateTests.cs

Adds a new section for preview versions to the dnvm releases json file. This will allow for two release trains: stable and preview.
(cherry picked from commit 2e783564f5bc4d7c3216b0a9615e38bc414987b7)

Allow enabling preview versions (#180)

---

.config/dotnet-tools.json

Works around versioning problems with prerelease tags.

Downgrade gitversion to 5.11.0

---

src/dnvm/Channel.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/Utilities/Utilities.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/TrackTests.cs

(cherry picked from commit e8b17b87e0a4d82eae2f53e93b740a2eb63100c7)

Support tracking feature channels (#186)

---

src/dnvm/DnvmEnv.cs
test/IntegrationTests/SelfInstallTests.cs
test/UnitTests/ManifestTests.cs
test/UnitTests/SelectTests.cs

When I run `dnvm restore` on Windows I get the following error:
```
Unhandled exception. System.ArgumentException: Path `C:/Projects/dnvm/global.json` must be absolute (Parameter 'path')
at Zio.UPathExtensions.AssertAbsolute(UPath, String) + 0x1a7
at Zio.FileSystems.FileSystem.ValidatePath(UPath, String, Boolean) + 0x66
at Zio.FileSystems.FileSystem.FileExists(UPath) + 0x2e
at Dnvm.RestoreCommand.<Run>d__1.MoveNext() + 0xa9
--- End of stack trace from previous location ---
at Dnvm.Program.<Dnvm>d__3.MoveNext() + 0x4a7
--- End of stack trace from previous location ---
at Dnvm.Program.<Main>d__1.MoveNext() + 0x259
--- End of stack trace from previous location ---
at Dnvm.Program.<Main>(String[] args) + 0x28
```
This is because on Windows, `UPath(Environment.CurrentDirectory)` returns a …

Fix restore command absolute path error for Windows

---

src/dnvm/Program.cs

This is used both for display purposes and updating the copy of dnvm.

Include the preview spec in the dnvm version

---

src/Serde.CmdLine/CmdLine.cs
src/Serde.CmdLine/Serde.CmdLine.csproj
src/dnvm/CommandLineArguments.cs
src/dnvm/DotnetReleasesIndex.cs
src/dnvm/InstallCommand.cs
src/dnvm/Program.cs
src/dnvm/PruneCommand.cs
src/dnvm/SelectCommand.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/UninstallCommand.cs
src/dnvm/UntrackCommand.cs
src/dnvm/UpdateCommand.cs
test/Serde.CmdLine.Test/CliTests.cs
test/Serde.CmdLine.Test/ParsedArgsOrHelpInfosExt.cs
test/Serde.CmdLine.Test/SubCommandTests.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/InstallTests.cs
test/UnitTests/SelectTests.cs
test/UnitTests/TrackTests.cs
test/UnitTests/UninstallTests.cs
test/UnitTests/UntrackTests.cs
test/UnitTests/UpdateTests.cs

It was mostly duplicated with the actual serialize/deserialize command object. If a particular command still needed a lot of options, a new options class was created in the command's class. Otherwise, the args now live in the former Command classes.

Remove commandlinearguments record

---

src/dnvm/CommandLineArguments.cs
src/dnvm/InstallCommand.cs
src/dnvm/ManifestUtils.cs
src/dnvm/Program.cs
src/dnvm/RestoreCommand.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/RestoreTests.cs

This changes the behavior of `dnvm restore`.
Before, restore always did a local restore to the .dotnet directory that matched the global.json. Now the default behavior is to install to the "global" dnvm directory for the user.
This is likely a better default because it allows the user to use `dnvm restore` across many repos without installing duplicate SDK versions. The previous behavior is available via `--local|-l`.
I also added a log statement to show the global.json parsed and roll forward calculated values. A few times I forgot about roll forward rules and got unexpected results, so the log statement helps explain where blame resides 🙃.

Add --local flag to restore

---

.github/workflows/ci.yml
.github/workflows/publish.yml

The build machine ends up as a glibc dependency for the built binary. By moving back to 22.04 we'll move the glibc dependency back as well.

Move linux distro version back to 22.04

---

src/dnvm/InstallCommand.cs
src/dnvm/Logger.cs
src/dnvm/RestoreCommand.cs
src/dnvm/SelectCommand.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/UntrackCommand.cs
src/dnvm/UpdateCommand.cs
test/UnitTests/RestoreTests.cs
test/UnitTests/SelectTests.cs

Add color to warnings and errors in the console to make them more noticeable. I also added a single newline of padding before and after warnings and errors to make them stand out, which was sometimes being done ad-hoc with empty log statements.
Here's an example warning and error:

Colorize warnings / error messages

---

src/dnvm/ManifestSchema/Manifest.cs
src/dnvm/UpdateCommand.cs
test/Shared/MockServer.cs
test/UnitTests/UpdateTests.cs

The old CLI didn't guard against installing the same SDK into multiple dirs, so it's possible for an update command to see the old dirs in the manifest. This avoids an exception in that case and updates all dirs.

Fix update tracking for dirs

---

src/dnvm/DnvmEnv.cs
src/dnvm/InstallCommand.cs
src/dnvm/ListCommand.cs
src/dnvm/Logger.cs
src/dnvm/Program.cs
src/dnvm/RestoreCommand.cs
src/dnvm/SelectCommand.cs
src/dnvm/SelfInstallCommand.cs
src/dnvm/TrackCommand.cs
src/dnvm/UninstallCommand.cs
src/dnvm/UntrackCommand.cs
src/dnvm/UpdateCommand.cs
src/dnvm/Utilities/IAnsiConsoleExt.cs
src/dnvm/Utilities/Utilities.cs
test/IntegrationTests/IntegrationTests.csproj
test/IntegrationTests/SelfInstallTests.cs
test/IntegrationTests/UpdateTests.cs
test/Shared/Dnvm.Test.Shared.csproj
test/Shared/TestOptions.cs
test/UnitTests/InstallTests.cs
test/UnitTests/ListTests.cs
test/UnitTests/RestoreTests.cs
test/UnitTests/SelectTests.cs
test/UnitTests/TrackTests.cs
test/UnitTests/UninstallTests.cs
test/UnitTests/UntrackTests.cs
test/UnitTests/UpdateTests.cs

dnvm really has two output streams: a user output stream and a diagnostics output stream. This change separates them and puts the diag stream to standard error.

Separate writing to the console from logging

---

src/dnvm/DnvmEnv.cs
src/dnvm/InstallCommand.cs

There were two problems:
1. The code was incorrectly detecting failure to get the build from the index
2. The CI download link for .NET changed, and daily builds are only on the CI server.

Fix downloading daily builds

---

src/dnvm/CommandLineArguments.cs
src/dnvm/InstallCommand.cs
src/dnvm/Utilities/Utilities.cs
test/UnitTests/CommandLineTests.cs
test/UnitTests/InstallTests.cs

Adds a command line arg '-d | --directory' to dotnet install.

Allow installing an sdk to a target path

---

src/dnvm/SelfInstallCommand.cs
test/IntegrationTests/SelfInstallTests.cs
test/Shared/ConditionalTheory.cs

A bug caused empty shell files to not be updated when doing a self-install.
Fixes https://github.com/dn-vm/dnvm/issues/223

Update shell files with no content

---

src/dnvm/Encoding.cs
src/dnvm/Manifest.cs
src/dnvm/Program.cs
src/dnvm/UpdateCommand.cs
test/Shared/MockServer.cs

Uses BOM, doesn't throw on invalid

Default dotnet encoding is broken

---

src/dnvm/InstallCommand.cs
src/dnvm/Utilities/Extensions.cs
test/UnitTests/InstallTests.cs

I've spent an embarrassing amount of time trying to figure out why dnvm can't find an sdk version, only to find out I've been pasting the runtime version (1 patch digit) rather than the sdk version (3 patch digits) I really wanted. A suggestion here would save me (and hopefully others) a bit of time staring at version numbers.

Suggest a 3 digit SDK patch version when a 1 or 2 digit patch is requested
