dn-vm/dnvm

- src/Install.cs
- src/Program.cs
- src/env.sh
Resource name was incorrect. Caused crashing during dnvm install.
> Fix resource reading for env.sh resource

- publish.sh
- src/Install.cs
- src/Update.cs
- src/Utilities.cs
Lets you cross-compile for a different RID than the one you're running on.
> Allow passing a RID to publish.sh

- src/CommandLineOptions.cs
- src/Install.cs
- src/LegacyManifests.cs
- src/Manifest.cs
- src/dnvm.csproj
- test/Shared/MockServer.cs
- test/UnitTests/InstallTests.cs
Make the install command install a channel and its latest version. This sets up channels to be tracked so that they can be regularly updated.
> Better support for channels

- src/dnvm/Install.cs
- test/IntegrationTests/SelfInstallTests.cs
Add some more text, include spacing, and add warning for System Path on Windows.
> Improve formatting for interactive

- src/dnvm/Update.cs
- test/IntegrationTests/SelfInstallTests.cs
- test/UnitTests/UpdateTests.cs
Also checks to see if there's a new version of dnvm when `dnvm update` is run, and prints out a message if there is something new.
> Check for self-update on `dnvm update`

- src/dnvm/CommandLineOptions.cs
- src/dnvm/GlobalOptions.cs
- src/dnvm/Install.cs
- src/dnvm/LegacyManifests/ManifestV1.cs
- src/dnvm/LegacyManifests/ManifestV2.cs
- src/dnvm/Manifest.cs
- src/dnvm/Update.cs
- test/IntegrationTests/SelfInstallTests.cs
- test/Shared/Assets.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/UpdateTests.cs
Parameterizes many locations to allow for non-default SDK install directories. No functional change.
> [NFC] Refactor to support multiple SDK install directories

- src/dnvm/CommandLineOptions.cs
- src/dnvm/Install.cs
- src/dnvm/List.cs
- src/dnvm/Manifest.cs
- src/dnvm/Program.cs
- src/dnvm/Select.cs
- src/dnvm/Update.cs
- test/Shared/MockServer.cs
- test/UnitTests/ListTests.cs
- test/UnitTests/SelectTests.cs
'dnvm select' lets the user choose a different active SDK, as used through the 'dotnet' command.
> Add select command

- .github/workflows/ci.yml
- .github/workflows/makeRelease.yml
- .github/workflows/publish.yml
- publish.ps1
- publish.sh
- src/dnvm/dnvm.csproj
- test/IntegrationTests/IntegrationTests.csproj
- test/Shared/Dnvm.Test.Shared.csproj
- test/UnitTests/UnitTests.csproj
> Move to net8 previews

- src/dnvm/DnvmFs.cs
- src/dnvm/Install.cs
- src/dnvm/LegacyManifests/ManifestV3.cs
- src/dnvm/Manifest.cs
- src/dnvm/Select.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/Update.cs
- src/dnvm/Utilities.cs
- test/UnitTests/ManifestTests.cs
Uses DnvmFs instead of string paths in more places.
> Refactor to avoid paths in more places

- src/dnvm/InstallCommand.cs
- src/dnvm/ListCommand.cs
- src/dnvm/Logger.cs
- src/dnvm/Program.cs
- src/dnvm/UpdateCommand.cs
- src/dnvm/Utilities/Utilities.cs
- src/dnvm/dnvm.csproj
- test/IntegrationTests/UpdateTests.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/ListTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/UnitTests.csproj
- test/UnitTests/UpdateTests.cs
Also use Spectre.Console to format dnvm list.
> Use Spectre.Console for logging/printing

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- publish.sh
- src/dnvm/InstallCommand.cs
- src/dnvm/UpdateCommand.cs
- src/dnvm/Utilities/Utilities.cs
- test/IntegrationTests/IntegrationTests.csproj
- test/IntegrationTests/SelfInstallTests.cs
- test/IntegrationTests/UpdateTests.cs
- test/Shared/MockServer.cs
- test/Shared/TaskScope.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/UpdateTests.cs
> Add support for TaskScope in testing

- publish.ps1
- test/Shared/MockServer.cs
New publish output directory also affects Windows
> Fix windows publish

- src/dnvm/DnvmFs.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/UpdateCommand.cs
- src/dnvm/Utilities/Utilities.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/UpdateTests.cs
Try to obsolete more instances of passing paths around.
> Use dnvmfs in more places

- src/dnvm/DnvmEnv.cs
- src/dnvm/GlobalOptions.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/Program.cs
- src/dnvm/SelectCommand.cs
- src/dnvm/SelfInstallCommand.cs
- test/IntegrationTests/SelfInstallTests.cs
- test/Shared/TestOptions.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/ListTests.cs
- test/UnitTests/SelectTests.cs
All code should now use DnvmEnv.Vfs for accessing the DnvmHome location.
> Remove DnvmHome from GlobalOptions

- src/dnvm/DnvmEnv.cs
- src/dnvm/GlobalOptions.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/UpdateCommand.cs
- test/IntegrationTests/VersionCheck.cs
- test/Shared/TestOptions.cs
- test/UnitTests/UpdateTests.cs
Consolidate more of GlobalOptions onto DnvmEnv
> Move feed settings to DnvmEnv

- src/dnvm/ListCommand.cs
- src/dnvm/ManifestSchema/Manifest.cs
- src/dnvm/ManifestSchema/ManifestV6.cs
- src/dnvm/ManifestUtils.cs
- src/dnvm/SelectCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/UntrackCommand.cs
- src/dnvm/UpdateCommand.cs
- test/Shared/MockServer.cs
- test/UnitTests/ManifestTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/TrackTests.cs
- test/UnitTests/UninstallTests.cs
- test/UnitTests/UntrackTests.cs
- test/UnitTests/UpdateTests.cs
Fix bugs where you couldn't track after untracking, and double untracking didn't correctly fail.
> Properly handle tracking and untracking

- src/dnvm/CommandLineArguments.cs
- src/dnvm/DotnetReleasesIndex.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/ManifestSchema/ManifestV5.cs
- src/dnvm/ManifestUtils.cs
- src/dnvm/Program.cs
- src/dnvm/SelectCommand.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/UpdateCommand.cs
- src/dnvm/Utilities/Utilities.cs
- test/Shared/MockServer.cs
- test/UnitTests/CommandLineTests.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/ManifestTests.cs
- test/UnitTests/TrackTests.cs
- test/UnitTests/UpdateTests.cs
Allows installing arbitrary SDK versions.
Fixes #119
> Add 'install' command 

- src/dnvm/UpdateCommand.cs
- src/dnvm/Utilities/Utilities.cs
- test/Shared/Assets.cs
Moving a file to a target requires the original to be deleted.
> Delete target files before moving over

- src/dnvm/DotnetReleasesIndex.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/UpdateCommand.cs
- test/Shared/MockServer.cs
- test/Shared/TestUtils.cs
- test/UnitTests/UpdateTests.cs
The new install has a progress bar, so it should be used as much as possible.
> Use new install method in Update

- src/dnvm/TrackCommand.cs
Just noticed a typo on this error message.
> Update error message

- src/dnvm/DnvmEnv.cs
- src/dnvm/Utilities/Utilities.cs
- test/IntegrationTests/SelfInstallTests.cs
- test/Shared/Assets.cs
- test/Shared/TestOptions.cs
- test/UnitTests/InstallTests.cs
Also add test for updating SDKs while dotnet is running
> Improve perf of file system abstractions

- src/dnvm/CommandLineArguments.cs
- test/UnitTests/CommandLineTests.cs
> Treat no command as a known command and print help

- src/dnvm/ListCommand.cs
- test/Shared/DisposableDirectory.cs
- test/UnitTests/ListTests.cs
> Print DNVM home in 'dnvm list'

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Directory.Packages.props
- global.json
- src/Serde.CmdLine/Deserializer.DeserializeType.cs
- src/dnvm/CommandLineArguments.cs
- src/dnvm/DnvmReleases.cs
- src/dnvm/ManifestSchema/ManifestV1.cs
- src/dnvm/ManifestUtils.cs
- src/dnvm/ScalarDeserializer.cs
- src/dnvm/Utilities/EqArray.cs
- src/dnvm/Utilities/ProcUtil.cs
- src/dnvm/Utilities/Utilities.cs
- src/dnvm/dnvm.csproj
- test/IntegrationTests/IntegrationTests.csproj
- test/Serde.CmdLine.Test/Serde.CmdLine.Test.csproj
- test/Shared/Dnvm.Test.Shared.csproj
- test/Shared/MockServer.cs
- test/UnitTests/UnitTests.csproj
Brings the size down from 12 MB to 10 MB.
> Move to net9 and move to records from record structs

- src/dnvm/InstallCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/UpdateCommand.cs
- test/Shared/MockServer.cs
- test/UnitTests/InstallTests.cs
Dnvm was always looking at the newest patch SDK, which means it wasn't finding SDKs that were superseded by newer patch versions.
> Fix bug in installing out-of-date SDKs

- src/dnvm/Channel.cs
- src/dnvm/DotnetReleasesIndex.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/Utilities/Utilities.cs
- test/UnitTests/CommandLineTests.cs
- test/UnitTests/TrackTests.cs
I would find it useful, so I implemented it.
> Support tracking feature channels

- src/dnvm/DnvmEnv.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/UninstallCommand.cs
- test/IntegrationTests/SelfInstallTests.cs
- test/Shared/TestOptions.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/TrackTests.cs
- test/UnitTests/UninstallTests.cs
Fixes https://github.com/dn-vm/dnvm/issues/188 on Unix
> Write DNVM_HOME if non-standard

- src/Serde.CmdLine/CmdLine.cs
- src/Serde.CmdLine/Serde.CmdLine.csproj
- src/dnvm/CommandLineArguments.cs
- src/dnvm/DotnetReleasesIndex.cs
- src/dnvm/InstallCommand.cs
- src/dnvm/ManifestUtils.cs
- src/dnvm/Program.cs
- src/dnvm/PruneCommand.cs
- src/dnvm/RestoreCommand.cs
- src/dnvm/SelectCommand.cs
- src/dnvm/SelfInstallCommand.cs
- src/dnvm/TrackCommand.cs
- src/dnvm/UninstallCommand.cs
- src/dnvm/UntrackCommand.cs
- src/dnvm/UpdateCommand.cs
- test/Serde.CmdLine.Test/CliTests.cs
- test/Serde.CmdLine.Test/ParsedArgsOrHelpInfosExt.cs
- test/Serde.CmdLine.Test/SubCommandTests.cs
- test/UnitTests/CommandLineTests.cs
- test/UnitTests/InstallTests.cs
- test/UnitTests/RestoreTests.cs
- test/UnitTests/SelectTests.cs
- test/UnitTests/TrackTests.cs
- test/UnitTests/UninstallTests.cs
- test/UnitTests/UntrackTests.cs
- test/UnitTests/UpdateTests.cs
Will be part of a 0.7.1 update
> Backport fixes to stable

- src/dnvm/InstallCommand.cs
- src/dnvm/Program.cs
- src/dnvm/Utilities/Utilities.cs
(cherry picked from commit 66ddb376e2a1c4daec5a784c6043a4ce0e21ab22)
> Remove all traces of old muxer code (#214)

- Directory.Build.props
Bring everything up to date, and prepare for shipping 0.9.0
> Merge from stable back into preview

- tools/mk-keys/Program.cs
Verifying the public key beforehand is left up to the user.
> Change mk-keys verify-release to not use the root key.

- src/dnvm/UninstallCommand.cs
- test/Shared/MockServer.cs
- test/UnitTests/PruneTests.cs
- test/UnitTests/UninstallTests.cs
> Skip missing directories during delete
